// Copyright 2020-2023 Tecdrop. All rights reserved.
// Use of this source code is governed by an MIT-style license that can be
// found in the LICENSE file.

// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
// This font was generated by FlutterIcon.com, which is derived from Fontello.
//
// Font Awesome 5, Copyright (C) 2016 by Dave Gandy
// Author:    Dave Gandy
// License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
// Homepage:  http://fortawesome.github.com/Font-Awesome/

import 'package:flutter/widgets.dart';

const _kFontFam = 'Colortypist';
const String? _kFontPkg = null;

const IconData github = IconData(0xf09b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
